[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Need to set this explicitly because Netlify still uses an old value on local deploy previews
[build]
  publish = "public"
